apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "egress.fullname" . }}
data:
  config.yaml: |
{{- $cm := .Values.egress }}
{{- if .Values.livekitCredentials.secretName }}
{{- $cm = omit $cm "api_key" "api_secret" }}
{{- end }}
{{ toYaml $cm | nindent 4 }}
