apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testingress.fullname" . }}
  labels:
    {{- include "testingress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testingress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "testingress.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "testingress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.podHostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: INGRESS_CONFIG_BODY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "testingress.fullname" . }}
                  key: config.yaml
          ports:
            {{- if .Values.ingress.health_port }}
            - name: health
              containerPort: {{ .Values.ingress.health_port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.ingress.http_relay_port }}
            - name: http-relay
              containerPort: {{ .Values.ingress.http_relay_port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.ingress.rtmp_port }}
            - name: rtmp-port
              containerPort: {{ .Values.ingress.rtmp_port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.ingress.whip_port }}
            - name: whip-port
              containerPort: {{ .Values.ingress.whip_port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.ingress.prometheus_port }}
            - name: metrics
              containerPort: {{ .Values.ingress.prometheus_port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: health
          readinessProbe:
            httpGet:
              path: /
              port: health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
