apiVersion: v2
name: test-ingress
description: LiveKit Ingress (test chart) — RTMP/WHIP ingestion for EKS + Karpenter
type: application
version: 0.1.0
appVersion: "v1.4.3"

sources:
  - https://github.com/livekit/ingress
  - https://github.com/livekit/livekit-helm
